name: CI - Automated Tests

on:
  push:
    branches:
      - master
      - feature-1

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
      
      - name: Install dependencies
        run: npm install
      
      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test
